INSERT INTO `School_Unit` (`School_ID`, `School_Name`, `Address`, `Phone`, `Email`, `Principal_Name`, `Principal_Surname`)
VALUES
(1, 'School A', 'Address A', 123456789, 'schoola1@school.com', 'John', 'Smith'),
(2, 'School B', 'Address B', 234567891, 'schoolb2@school.com', 'Emily', 'Johnson'),
(3, 'School C', 'Address C', 345678912, 'schoolc3@school.com', 'Daniel', 'Brown'),
(4, 'School D', 'Address D', 456789123, 'schoold4@school.com', 'Michael', 'Davis'),
(5, 'School E', 'Address E', 567891234, 'schoole5@school.com', 'Emma', 'Miller'),
(6, 'School F', 'Address F', 678912345, 'schoolf6@school.com', 'Jose', 'Garcia'),
(7, 'School G', 'Address G', 789456123, 'schoolg7@school.com', 'Jonathan', 'Venezuela'),
(8, 'School H', 'Address H', 891234567, 'schoolh8@school.com', 'Mario', 'Ruiz'),


INSERT INTO `Category` (`Category_ID`, `Category_Name`)
VALUES
    (1, 'Fiction'),
    (2, 'Non-fiction'),
    (3, 'Mystery'),
    (4, 'Science fiction'),
    (5, 'Fantasy'),
    (6, 'Romance'),
    (7, 'Thriller'),
    (8, 'Historical fiction'),
    (9, 'Biography'),
    (10, 'Self-help'),
    (11, 'Science'),
    (12, 'Poetry'),
    (13, 'Travel'),
    (14, 'Horror'),
    (15, "Children's"),
    (16, 'Young adult'),
    (17, 'Humor'),
    (18, 'Philosophy'),
    (19, 'Art and photography'),
    (20, 'Business and finance');


INSERT INTO `Author` (`Author_ID`, `Author_Name`, `Author_Surname`)
VALUES
    (1, 'William', 'Shakespeare'),
    (2, 'J.K.', 'Rowling'),
    (3, 'Agatha', 'Christie'),
    (4, 'Stephen', 'King'),
    (5, 'J.R.R.', 'Tolkien'),
    (6, 'Charles', 'Dickens'),
    (7, 'Jane', 'Austen'),
    (8, 'Mark', 'Twain'),
    (9, 'George', 'Orwell'),
    (10, 'Ernest', 'Hemingway'),
    (11, 'Fyodor', 'Dostoevsky'),
    (12, 'Leo', 'Tolstoy'),
    (13, 'Harper', 'Lee'),
    (14, 'Toni', 'Morrison'),
    (15, 'Virginia', 'Woolf'),
    (16, 'Gabriel', 'Garcia Marquez'),
    (17, 'F.', 'Scott Fitzgerald'),
    (18, 'Arthur', 'Conan Doyle'),
    (19, 'Roald', 'Dahl'),
    (20, 'Victor', 'Hugo'),
    (21, 'Oscar', 'Wilde'),
    (22, 'William', 'Faulkner'),
    (23, 'Franz', 'Kafka'),
    (24, 'Aldous', 'Huxley'),
    (25, 'C.S.', 'Lewis'),
    (26, 'Kurt', 'Vonnegut'),
    (27, 'John', 'Steinbeck'),
    (28, 'H.P.', 'Lovecraft'),
    (29, 'H.G.', 'Wells'),
    (30, 'Margaret', 'Atwood'),
    (31, 'Salman', 'Rushdie'),
    (32, 'Gabriel', 'Garcia Marquez'),
    (33, 'Philip', 'K. Dick'),
    (34, 'John', 'Grisham'),
    (35, 'Isabel', 'Allende'),
    (36, 'Michael', 'Crichton'),
    (37, 'Neil', 'Gaiman'),
    (38, 'George', 'R.R. Martin'),
    (39, 'Dan', 'Brown'),
    (40, 'Ken', 'Follett'),
    (41, 'Paulo', 'Coelho'),
    (42, 'Terry', 'Pratchett'),
    (43, 'Suzanne', 'Collins'),
    (44, 'Rudyard', 'Kipling'),
    (45, 'James', 'Joyce'),
    (46, 'Emily', 'Bronte'),
    (47, 'Ray', 'Bradbury'),
    (48, 'Haruki', 'Murakami'),
    (49, 'Roald', 'Dahl'),
    (50, 'Isabel', 'Allende'),
    (51, 'Gabriel', 'Garcia Marquez'),
    (52, 'Agatha', 'Christie'),
    (53, 'Arthur C.', 'Clarke'),
    (54, 'Ursula K.', 'Le Guin'),
    (55, 'Cormac', 'McCarthy'),
    (56, 'Octavia', 'Butler'),
    (57, 'Margaret', 'Atwood'),
    (58, 'Donna', 'Tartt'),
    (59, 'Kazuo', 'Ishiguro'),
    (60, 'David', 'Mitchell');
